Repository mucsci-students/2023sp-420-Maryjane, pull requests merged in 2023-04, with the labels that each got.

#203 181 singleton design pattern
  README.md
  package.json
  src/model/Model.js
  tests/Model.test.js
Labels: documentation, enhancement, New Feature

#204 added codecov to ci
  .github/workflows/node.js.yml
  README.md
  src/controllers/CLI_Controller.js
Labels: New Feature

#206 fixed actions i think
  .github/workflows/node.js.yml
Labels: bug fix

#207 updated npm scripts
  README.md
  app.js
  package.json
Labels: enhancement, bug fix

#210 Fixed a bug where pangrams couldn't be guessed
  src/commands/newPuzzleCommands.js
Labels: bug fix

#216 151 fix gui horizontal spacing of hexagons optional
  package-lock.json
  package.json
  style.css
Labels: enhancement, bug fix, New Feature

#222 Update read me design pattern
  README.md
Labels: documentation

#226 update model with highscore
  src/commands/highScoreCommand.js
  src/model/Model.js
  src/views/GUI_View.js
Labels: documentation, enhancement

#229 added share img to cli
  src/controllers/CLI_Controller.js
  src/views/CLI_View.js
Labels: New Feature

#231 Fixing mvc
  src/commands/commands.js
  src/commands/fileCommands.js
  src/commands/newPuzzleCommands.js
  src/commands/shuffleCommands.js
  src/model/Model.js
  src/model/dict.js
  tests/Model.test.js
Labels: documentation, enhancement, New Feature

#235 New high score
  highScoreDict.json
  src/commands/fileCommands.js
  src/commands/guessCommands.js
  src/commands/highScoreCommand.js
  src/commands/newPuzzleCommands.js
  src/controllers/CLI_Controller.js
Labels: documentation, enhancement, bug fix

#244 Update ReadMe
  README.md
Labels: documentation
