Repository mucsci-students/2023sp-420-Maryjane, pull requests merged in 2023-03, with the labels that each got.

#141 G UI new puzzle from base
  bundle.js
  src/classes/Commands.js
  src/controllers/GUI_Controller.js
  src/views/GUI_View.js
Labels: enhancement, New Feature

#142 Local Database
  bundle.js
  index.html
  src/classes/Commands.js
  src/classes/Database.js
  src/controllers/CLI_Controller.js
  src/controllers/GUI_Controller.js
  src/database/MaryJane.js
  src/database/lib/mongodb.js
  src/initCLI.js
  src/initGUI.js
  src/model/Model.js
  src/views/CLI_View.js
  src/views/GUI_View.js
Labels: documentation, enhancement, bug fix, New Feature

#144 143 fixed rank and found words
  src/classes/Commands.js
Labels: bug fix

#146 97 gui help button 2
  index.html
  src/controllers/CLI_Controller.js
  src/views/CLI_View.js
Labels: enhancement

#147 Gui save load
  bundle.js
  index.html
  src/classes/Commands.js
  src/views/GUI_View.js
  test.html
Labels: documentation, enhancement, bug fix

#154 149 add save prompt to new puzzle function
  bundle.js
  package-lock.json
  package.json
  src/README.md
  src/controllers/CLI_Controller.js
  src/controllers/GUI_Controller.js
  src/views/GUI_View.js
  style.css
Labels: documentation, enhancement, bug fix, New Feature

#156 fixed show rank in CLI
  src/views/CLI_View.js
Labels: bug fix

#162 Changed Font for text area
  style.css
Labels: bug fix

#172 Mjlewis dev readme
  src/README.md
Labels: documentation

#174 updated database test file functions
  tests/Database.test.js
Labels: documentation, enhancement

#175 finished tests for guess command
  src/classes/Commands.js
  tests/Commands.test.js
Labels: bug fix

#191 added MVC design pattern to README
  README.md
Labels: New Feature

#198 187 add hint to cli view
  src/commands/hintCommands.js
  src/controllers/CLI_Controller.js
  src/views/CLI_View.js
Labels: enhancement, New Feature

#201 Updated design patterns in the README.md
  README.md
Labels: documentation, enhancement

#202 updated tests and actions
  .github/workflows/node.js.yml
  README.md
  src/model/Model.js
  tests/Model.test.js
Labels: documentation, enhancement, bug fix, New Feature
