Repository mucsci-students/2023sp-420-Maryjane, pull requests merged in 2023-02, with the labels that each got.

#19 Added and Implemented GameManager Class
  src/app.js
  src/classes/GameManager.js
Labels: enhancement

#20 Implemented some functionality to the guess command
  src/app.js
  src/classes/Commands.js
  src/classes/GameManager.js
  tests/tests.js
Labels: enhancement

#32 Finished guess command
  src/app.js
  src/classes/Commands.js
  tests/tests.js
Labels: documentation, enhancement

#34 added new puzzle command, making game playable
  src/app.js
  src/classes/Commands.js
Labels: enhancement

#39 Improved documentation
  src/app.js
Labels: documentation

#40 Added more functionality to the database class
  src/classes/Database.js
Labels: documentation, enhancement

#44 Finished new puzzle command
  src/app.js
  src/classes/Commands.js
  src/classes/GameManager.js
Labels: documentation, enhancement

#50 43 show rank command
  .gitignore
  src/app.js
  src/classes/Commands.js
Labels: documentation, enhancement

#54 Fixed Load-Command edge case bug.
  src/classes/Commands.js
Labels: bug

#56 updated the load, save , and exit commands
  .gitignore
  src/app.js
  src/classes/Commands.js
Labels: documentation, enhancement

#57 worked on rank command
  package-lock.json
  package.json
  src/app.js
  src/classes/Commands.js
  src/classes/Utils.js
  src/dictionary
Labels: documentation, enhancement

#66 fixed vulnerability
  package-lock.json
  package.json
  src/app.js
Labels: enhancement, bug fix

#60 Added show puzzle command.
  src/app.js
  src/classes/Commands.js
Labels: documentation, enhancement, help wanted

#69 Removed .bee and replaced with .json
  .gitignore
  src/classes/Commands.js
Labels: enhancement

#68 Obtained 100% code coverage for database.js
  tests/Database.test.js
Labels: enhancement

#61 Added style of both start up prompt and logo
  src/app.js
  src/classes/Commands.js
Labels: documentation

#67 Fixed the guess test
  .gitignore
  tests/Commands.test.js
Labels: bug fix

#72 fixed bugs from group meeting
  src/app.js
  src/classes/Commands.js
Labels: bug fix

#73 Fixed known bugs
  src/classes/Commands.js
Labels: documentation, enhancement, bug fix

#74 Updated readme
  README.md
Labels: documentation, enhancement

#76 Fixed bug in save command
  src/classes/Commands.js
Labels: enhancement, bug fix

#77 Added more detail to getting started section
  README.md
Labels: documentation, enhancement

#78 Made a simple test file for save command
  src/classes/Commands.js
  tests/FileSystemCommands.test.js
Labels: enhancement

#80 updated dev readme
  src/README.md
  tests/Database.test.js
Labels: documentation

#102 Mjl cli v0.1
  src/classes/Commands.js
Labels: enhancement, bug fix

#103 added new database package
  package-lock.json
  package.json
  src/README.md
  src/classes/Commands.js
Labels: enhancement

#104 Added mvc structure
  src/app.js
  src/classes/Commands.js
  src/classes/GameManager.js
  src/model/Model.js
Labels: enhancement

#105 Implemented CLI controller
  src/app.js
  src/controllers/CLI_Controller.js
  src/database.js
Labels: enhancement, bug fix

#106 fully integrated MVC CLI for now
  src/app.js
  src/classes/Commands.js
  src/controllers/CLI_Controller.js
  src/model/Model.js
  src/views/CLI_View.js
  src/views/View.js
Labels: documentation, enhancement

#109 Create static.yml
  .github/workflows/static.yml
Labels: New Feature

#112 Update README.md
  README.md
Labels: New Feature

#116 added node support to html
  .github/workflows/static.yml
  .gitignore
  index.html
  package-lock.json
  package.json
  src/gui.js
  src/views/GUI_View.js
Labels: enhancement, bug fix, New Feature

#118 Implemented base version of shuffle
  index.html
  package-lock.json
  package.json
  src/gui.js
  style.css
Labels: enhancement, New Feature

#119 updated gui to make it easier to add js code
  index.html
  package.json
  src/controllers/GUI_Controller.js
  src/initCLI.js
  src/initGUI.js
  style.css
Labels: documentation, enhancement, bug fix, New Feature

#120 Gui improvements
  index.html
  src/initGUI.js
Labels: bug fix

#121 Show puzzle g UI
  index.html
  src/initGUI.js
  src/views/GUI_View.js
  style.css
Labels: enhancement

#122 Mvc
  index.html
  package.json
  src/classes/Commands.js
  src/controllers/GUI_Controller.js
  src/initGUI.js
  src/views/GUI_View.js
Labels: enhancement, bug fix, New Feature

#123 fixed changes from last pr
  src/initGUI.js
  src/views/GUI_View.js
Labels: bug fix

#124 added a template to make it easier to fix html/css
  index2.html
  style2.css
Labels: documentation, enhancement

#125 Created is word from scratch
  index.html
  package-lock.json
  package.json
  src/classes/Commands.js
  src/dict.js
  src/initGUI.js
Labels: enhancement, bug fix

#126 updated index2 and style2 to include major changes
  honey.png
  index.html
  index2.html
  style.css
  style2.css
Labels: bug, documentation, enhancement

#127 Create node.js.yml
  .github/workflows/node.js.yml
  src/controllers/GUI_Controller.js
  tests/Commands.test.js
  tests/Database.test.js
  tests/FileSystemCommands.test.js
Labels: bug fix, New Feature

#131 Added Delete button
  bundle.js
  index.html
  src/controllers/GUI_Controller.js
  src/views/GUI_View.js
Labels: documentation, enhancement

#132 Gui enter button
  bundle.js
  index.html
  src/controllers/GUI_Controller.js
  src/initGUI.js
  src/views/GUI_View.js
  style.css
Labels: documentation, enhancement, bug fix

#133 Updated style
  bundle.js
  index.html
  src/classes/Commands.js
  src/controllers/GUI_Controller.js
  src/initGUI.js
  src/views/GUI_View.js
  style.css
Labels: documentation, enhancement, bug fix

#135 fixed gui bug and edited readme, commented out
  README.md
  bundle.js
  index.html
  src/views/GUI_View.js
  style.css
Labels: documentation, enhancement, bug fix

#136 improved documentation and coding style
  .gitignore
  bundle.js
  index.html
  src/README.md
  src/classes/Commands.js
  src/classes/Database.js
  src/controllers/CLI_Controller.js
  src/controllers/GUI_Controller.js
  src/dict.js
  src/initCLI.js
  src/initGUI.js
  src/views/CLI_View.js
  src/views/GUI_View.js
Labels: documentation

#137 updated nav bar and formatted index,css,and view
  bundle.js
  index.html
  src/views/GUI_View.js
  style.css
Labels: documentation, enhancement, bug fix

#138 Gui rank 2
  bundle.js
  index.html
  src/controllers/GUI_Controller.js
  src/model/Model.js
  src/views/GUI_View.js
Labels: enhancement, New Feature

#139 Update README.md
  README.md
Labels: documentation
